/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;
/**
 *
 * @author Manuel Cañamaque
 */
public class Editor extends javax.swing.JDialog {
    private static int numeroTabla;
    private static boolean conDatos;   
    
    public Editor(java.awt.Frame parent, boolean modal, int numeroTabla, boolean conDatos) {
        super(parent, modal);
        
        initComponents();
        this.setLocationRelativeTo(parent);
        
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        
        if(conDatos){
            switch(Main.indexSelected){
                case 1:
            }
            this.setTitle("Editar");
        }else{
            this.setTitle("Añadir");
        }
        
        this.numeroTabla=numeroTabla;
        this.conDatos=conDatos;
        
        switch(numeroTabla){
            case 0:
                if(conDatos){
                    this.setTitle("Editar Cliente");
                }else{
                    this.setTitle("Añadir Cliente");
                }
                EditarCliente panelClientes = new EditarCliente(this.conDatos);
                this.add(panelClientes);
                pack();
                break;
            case 1:
                if(conDatos){
                    this.setTitle("Editar Proveedor");
                }else{
                    this.setTitle("Añadir Proveedor");
                }
                EditarProveedor panelProveedores = new EditarProveedor(this.conDatos);
                this.add(panelProveedores);
                pack();
                break;
            case 2:
                if(conDatos){
                    this.setTitle("Editar Categoria");
                }else{
                    this.setTitle("Añadir Categoria");
                }
                EditarCategoria panelCategorias = new EditarCategoria(this.conDatos);
                this.add(panelCategorias);
                pack();
                break;
            case 3:
                if(conDatos){
                    this.setTitle("Editar Marca");
                }else{
                    this.setTitle("Añadir Marca");
                }
                EditarMarca panelMarcas= new EditarMarca(this.conDatos);
                this.add(panelMarcas);
                pack();
                break;
            case 4:
                if(conDatos){
                    this.setTitle("Editar Articulo");
                }else{
                    this.setTitle("Añadir Articulo");
                }
                EditarArticulo panelArticulos= new EditarArticulo(this.conDatos);
                this.add(panelArticulos);
                pack();
                break;
            case 5:
                if(conDatos){
                    this.setTitle("Editar Linea Venta");
                }else{
                    this.setTitle("Añadir Linea venta");
                }
                EditarLineaVenta panelLineasVentas= new EditarLineaVenta(this.conDatos);
                this.add(panelLineasVentas);
                pack();
                break;
            case 6:
                if(conDatos){
                    this.setTitle("Editar Venta");
                }else{
                    this.setTitle("Añadir Venta");
                }
                EditarVenta panelVentas= new EditarVenta(this.conDatos);
                this.add(panelVentas);
                pack();
                break;
        } 
    }  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Editor dialog = new Editor(new javax.swing.JFrame(), true, numeroTabla, conDatos);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
