/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import BaseDatos.BaseDatos;
import BaseDatos.Values;
import Clases.Cliente;
import Clases.ClienteList;
import Clases.Venta;
import Clases.VentaList;
import Renders.ComboBoxRender;
import Renders.ControlCaracteres;
import java.math.BigDecimal;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Manuel Cañamaque
 */
public class EditarVenta extends javax.swing.JPanel {
    boolean conDatos;
    Venta venta;
    /**
     * Creates new form EditarVenta
     */
    public EditarVenta(boolean conDatos) {
        initComponents();
        this.conDatos=conDatos;
        
        //Añadimos los ComboBox y los Renders
        jComboBox1.setModel(new DefaultComboBoxModel(ClienteList.getArray()));
        jComboBox1.setRenderer(new ComboBoxRender());
        
        //Obtenemos la Venta seleccionada
        venta = VentaList.getVentaAt(Main.getRowSelected());
        
        //Asignar Documents a los campos de texto.
        jTextField1.setDocument(new ControlCaracteres(Values.iva_Venta));        
        jTextField2.setDocument(new ControlCaracteres(Values.importeVenta_Venta));
        jTextField3.setDocument(new ControlCaracteres(Values.importeVentaConIva_Venta));
        
        //Rellenamos los jTextFields si es para editar
        if(conDatos){
            jTextField1.setText(""+venta.getIva());
            jTextField2.setText(""+venta.getImporteVenta());
            jTextField3.setText(""+venta.getImporteVentaConIva());
            jDateChooser1.setDate(venta.getFechaVenta());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        boton_Guardar_Venta = new javax.swing.JButton();
        boton_Cancelar_Venta = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        botonCliente = new javax.swing.JButton();

        jLabel1.setText("Cliente:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Fecha Venta:");

        jLabel3.setText("Iva:");

        jTextField1.setColumns(3);

        jLabel4.setText("ImporteVenta:");

        jTextField2.setColumns(10);

        jLabel5.setText("ImporteVentaConIva:");

        jTextField3.setColumns(10);

        boton_Guardar_Venta.setText("Guardar");
        boton_Guardar_Venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Guardar_VentaActionPerformed(evt);
            }
        });

        boton_Cancelar_Venta.setText("Cancelar");
        boton_Cancelar_Venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Cancelar_VentaActionPerformed(evt);
            }
        });

        jDateChooser1.setMinimumSize(new java.awt.Dimension(120, 25));
        jDateChooser1.setPreferredSize(new java.awt.Dimension(120, 25));

        botonCliente.setText("..Nuevo");
        botonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boton_Guardar_Venta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton_Cancelar_Venta)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonCliente))
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_Guardar_Venta)
                    .addComponent(boton_Cancelar_Venta))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void boton_Cancelar_VentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Cancelar_VentaActionPerformed
        int result = JOptionPane.showConfirmDialog(this, 
        "¿Está seguro de que desea salir sin guardar los cambios?","Salir sin guardar", JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_OPTION){ 
            SwingUtilities.getWindowAncestor(this).setVisible(false);
            SwingUtilities.getWindowAncestor(this).dispose();
        }
    }//GEN-LAST:event_boton_Cancelar_VentaActionPerformed

    private void boton_Guardar_VentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Guardar_VentaActionPerformed
        boolean correcto=true;
        // Comenzamos una nueva transaccion si no hay ninguna activa
        if(!BaseDatos.entityManager.getTransaction().isActive()){
            BaseDatos.entityManager.getTransaction().begin();
        }
        //Comprobamos que los campos no estan vacios.
        if("".equals(jTextField1.getText()) || "".equals(jTextField2.getText())
            || "".equals(jTextField3.getText()) || jDateChooser1.getDate()==null){
            correcto=false;
        }else{
            int iva = 0;
            BigDecimal importeVenta = null;
            BigDecimal importeVentaConIva = null;
            try {
                iva = Integer.valueOf(jTextField1.getText());
                importeVenta = BigDecimal.valueOf(Double.valueOf(jTextField2.getText()));
                importeVentaConIva = BigDecimal.valueOf(Double.valueOf(jTextField3.getText()));
            } catch (NumberFormatException e) {
                correcto=false;        
            }
            //Si es para editar, asignamos los valores al articulo.
            if(conDatos){
                venta.setCliente((Cliente)jComboBox1.getSelectedItem());
                venta.setFechaVenta(jDateChooser1.getDate());
                venta.setIva(iva);
                venta.setImporteVenta(importeVenta);
                venta.setImporteVentaConIva(importeVentaConIva);      
                BaseDatos.entityManager.merge(venta);
            }else{
                //Si es una venta nueva, la creamos, le cambiamos los datos y la guardamos
                Venta ventaNueva = new Venta();
                ventaNueva.setCliente((Cliente)jComboBox1.getSelectedItem());
                ventaNueva.setFechaVenta(jDateChooser1.getDate());
                ventaNueva.setIva(iva);
                ventaNueva.setImporteVenta(importeVenta);
                ventaNueva.setImporteVentaConIva(importeVentaConIva);
                BaseDatos.entityManager.persist(ventaNueva);
                VentaList.addVenta(ventaNueva);
            }
        }
        //Si todo esta correcto, confirmamos la transaccion ,informamos al tableModel de los cambios
        // y cerramos la ventana
        if(correcto){    
            BaseDatos.entityManager.getTransaction().commit();            
            BaseDatos.entityManager.getTransaction().begin();

            if(conDatos){
                //Informamos de que se ha editado una fila
                Main.modelosTablas[6].fireTableRowsUpdated(Main.rowSelected, Main.rowSelected);                    
            }else{
                //Informamos de que se ha insertado una fila nueva y la seleccionamos por defecto
                Main.modelosTablas[6].fireTableRowsInserted(VentaList.size()-1, VentaList.size()-1);
                Main.tablas[6].setRowSelectionInterval(VentaList.size()-1, VentaList.size()-1);
            }
            //Llamamos al JDialog padre y lo cerramos.
            SwingUtilities.getWindowAncestor(this).setVisible(false);
            SwingUtilities.getWindowAncestor(this).dispose();
        }else{
            //Si no son correctos los datos, deshacemos los cambios e informamos al usuario
            BaseDatos.entityManager.getTransaction().rollback();
            BaseDatos.entityManager.getTransaction().begin();
            JOptionPane.showMessageDialog(this, "No se han podido guardar los datos, compruebe los campos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_boton_Guardar_VentaActionPerformed

    private void botonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonClienteActionPerformed
        JDialog editor = new JDialog();        
        EditarCliente editarCliente = new EditarCliente(false);
        editor.add(editarCliente);
        editor.setModal(true);
        editor.setLocationRelativeTo(this.getParent());
        editor.pack();
        editor.setVisible(true);
        jComboBox1.setModel(new DefaultComboBoxModel(ClienteList.getArray()));
    }//GEN-LAST:event_botonClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCliente;
    private javax.swing.JButton boton_Cancelar_Venta;
    private javax.swing.JButton boton_Guardar_Venta;
    private javax.swing.JComboBox jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
