/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import BaseDatos.BaseDatos;
import BaseDatos.Values;
import Clases.Categoria;
import Clases.CategoriaList;
import Renders.ControlCaracteres;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Manuel Cañamaque
 */
public class EditarCategoria extends javax.swing.JPanel {
    boolean conDatos;
    Categoria categoria;
    /**
     * Creates new form EditarCategoria
     */
    public EditarCategoria(boolean conDatos) {
        initComponents();
        this.conDatos=conDatos;
        
        //Obtenemos la categoria seleccionada
        categoria = CategoriaList.getCategoriaAt(Main.getRowSelected());
        
        //Asignar Documents a los campos de texto.
        jTextField1.setDocument(new ControlCaracteres(Values.nombre_Categoria));
        
        //Rellenamos los jTextFields si es para editar
        if(conDatos){
            jTextField1.setText(categoria.getNombre());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        boton_Guardar_Categoria = new javax.swing.JButton();
        boton_Cancelar_Categoria = new javax.swing.JButton();

        jLabel1.setText("Nombre:");

        jTextField1.setColumns(10);

        boton_Guardar_Categoria.setText("Guardar");
        boton_Guardar_Categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Guardar_CategoriaActionPerformed(evt);
            }
        });

        boton_Cancelar_Categoria.setText("Cancelar");
        boton_Cancelar_Categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Cancelar_CategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boton_Guardar_Categoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton_Cancelar_Categoria)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_Guardar_Categoria)
                    .addComponent(boton_Cancelar_Categoria))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void boton_Cancelar_CategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Cancelar_CategoriaActionPerformed
        int result = JOptionPane.showConfirmDialog(this, 
        "¿Está seguro de que desea salir sin guardar los cambios?","Salir sin guardar", JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_OPTION){ 
            SwingUtilities.getWindowAncestor(this).setVisible(false);
            SwingUtilities.getWindowAncestor(this).dispose();
        }
    }//GEN-LAST:event_boton_Cancelar_CategoriaActionPerformed

    private void boton_Guardar_CategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Guardar_CategoriaActionPerformed
        boolean correcto=true;
        // Comenzamos una nueva transaccion si no hay ninguna activa
        if(!BaseDatos.entityManager.getTransaction().isActive()){
            BaseDatos.entityManager.getTransaction().begin();
        }
        //Comprobamos que los campos no estan vacios.
        if("".equals(jTextField1.getText())){
            correcto=false;
        }else{            
            //Si es para editar, asignamos los valores a la categoria.
            if(conDatos){
                categoria.setNombre(jTextField1.getText());               
                BaseDatos.entityManager.merge(categoria);
            }else{
                //Si es una nueva categoria, la creamos, le cambiamos los datos y la guardamos
                Categoria categoriaNueva= new Categoria();
                categoriaNueva.setNombre(jTextField1.getText());
                BaseDatos.entityManager.persist(categoriaNueva);
                CategoriaList.addCategoria(categoriaNueva);
            }
        }
        //Si todo esta correcto, confirmamos la transaccion ,informamos al tableModel de los cambios
        // y cerramos la ventana
        if(correcto){    
            BaseDatos.entityManager.getTransaction().commit();            
            BaseDatos.entityManager.getTransaction().begin();

            if(conDatos){
                //Informamos de que se ha editado una fila
                Main.modelosTablas[2].fireTableRowsUpdated(Main.rowSelected, Main.rowSelected);                    
            }else{
                //Informamos de que se ha insertado una fila nueva y la seleccionamos por defecto
                Main.modelosTablas[2].fireTableRowsInserted(CategoriaList.size()-1, CategoriaList.size()-1);
                Main.tablas[2].setRowSelectionInterval(CategoriaList.size()-1, CategoriaList.size()-1);
            }
            //Llamamos al JDialog padre y lo cerramos.
            SwingUtilities.getWindowAncestor(this).setVisible(false);
            SwingUtilities.getWindowAncestor(this).dispose();
        }else{
            //Si no son correctos los datos, deshacemos los cambios e informamos al usuario
            BaseDatos.entityManager.getTransaction().rollback();
            BaseDatos.entityManager.getTransaction().begin();
            JOptionPane.showMessageDialog(this, "No se han podido guardar los datos, compruebe los campos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_boton_Guardar_CategoriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_Cancelar_Categoria;
    private javax.swing.JButton boton_Guardar_Categoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
