/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import BaseDatos.BaseDatos;
import BaseDatos.Values;
import Clases.Articulo;
import Clases.ArticuloList;
import Clases.Lineaventa;
import Clases.LineaVentaList;
import Clases.Venta;
import Clases.VentaList;
import Renders.ComboBoxRender;
import Renders.ControlCaracteres;
import java.math.BigDecimal;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Manuel Cañamaque
 */
public class EditarLineaVenta extends javax.swing.JPanel {
    boolean conDatos;
    Lineaventa lineaVenta;
    /**
     * Creates new form EditarLineaVenta
     */
    public EditarLineaVenta(boolean conDatos) {
        initComponents();
        this.conDatos=conDatos;
        
        //Añadir ComboBox y Renders
        jComboBox1.setModel(new DefaultComboBoxModel(VentaList.getArray()));
        jComboBox1.setRenderer(new ComboBoxRender());
        jComboBox2.setModel(new DefaultComboBoxModel(ArticuloList.getArray()));
        jComboBox2.setRenderer(new ComboBoxRender());
        
        //Obtenemos la lineaVenta seleccionada
        lineaVenta = LineaVentaList.getLineaVentaAt(Main.getRowSelected());
        
        //Asignar Documents a los campos de texto.
        jTextField1.setDocument(new ControlCaracteres(Values.cantidad_LineaVenta));        
        jTextField2.setDocument(new ControlCaracteres(Values.importeLineaVenta_LineaVenta));
        
        //Rellenamos los jTextFields si es para editar
        if(conDatos){
            jTextField1.setText(""+lineaVenta.getCantidad());
            jTextField2.setText(""+lineaVenta.getImporteLineaVenta());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        boton_Guardar_LineaVenta = new javax.swing.JButton();
        boton_Cancelar_LineaVenta = new javax.swing.JButton();
        botonVenta = new javax.swing.JButton();
        botonArticulo = new javax.swing.JButton();

        jLabel1.setText("Venta:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Articulo:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Cantidad:");

        jTextField1.setColumns(5);

        jLabel4.setText("ImporteLineaVenta:");

        jTextField2.setColumns(10);

        boton_Guardar_LineaVenta.setText("Guardar");
        boton_Guardar_LineaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Guardar_LineaVentaActionPerformed(evt);
            }
        });

        boton_Cancelar_LineaVenta.setText("Cancelar");
        boton_Cancelar_LineaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Cancelar_LineaVentaActionPerformed(evt);
            }
        });

        botonVenta.setText("..Nueva");
        botonVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVentaActionPerformed(evt);
            }
        });

        botonArticulo.setText("..Nuevo");
        botonArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonArticuloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonVenta))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boton_Guardar_LineaVenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton_Cancelar_LineaVenta)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonArticulo)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonArticulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_Guardar_LineaVenta)
                    .addComponent(boton_Cancelar_LineaVenta))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void boton_Cancelar_LineaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Cancelar_LineaVentaActionPerformed
        int result = JOptionPane.showConfirmDialog(this, 
        "¿Está seguro de que desea salir sin guardar los cambios?","Salir sin guardar", JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_OPTION){ 
            SwingUtilities.getWindowAncestor(this).setVisible(false);
            SwingUtilities.getWindowAncestor(this).dispose();
        }
    }//GEN-LAST:event_boton_Cancelar_LineaVentaActionPerformed

    private void boton_Guardar_LineaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Guardar_LineaVentaActionPerformed
        boolean correcto=true;
        // Comenzamos una nueva transaccion si no hay ninguna activa
        if(!BaseDatos.entityManager.getTransaction().isActive()){
            BaseDatos.entityManager.getTransaction().begin();
        }
        //Comprobamos que los campos no estan vacios.
        if("".equals(jTextField1.getText()) || "".equals(jTextField2.getText())){
            correcto=false;
        }else{
            int cantidad = 0;
            BigDecimal importeLineaVenta = null;
            try {
                cantidad = Integer.valueOf(jTextField1.getText());
                importeLineaVenta = BigDecimal.valueOf(Double.valueOf(jTextField2.getText()));
            } catch (NumberFormatException e) {
                correcto=false;        
            }
            //Si es para editar, asignamos los valores al articulo.
            if(conDatos){
                lineaVenta.setVenta((Venta)jComboBox1.getSelectedItem());
                lineaVenta.setArticulo((Articulo)jComboBox2.getSelectedItem());
                lineaVenta.setCantidad(cantidad);
                lineaVenta.setImporteLineaVenta(importeLineaVenta);
                BaseDatos.entityManager.merge(lineaVenta);
            }else{
                //Si es una lineaVenta nueva, la creamos, le cambiamos los datos y la guardamos
                Lineaventa lineaVentaNueva = new Lineaventa();
                lineaVentaNueva.setVenta((Venta)jComboBox1.getSelectedItem());
                lineaVentaNueva.setArticulo((Articulo)jComboBox2.getSelectedItem());
                lineaVentaNueva.setCantidad(cantidad);
                lineaVentaNueva.setImporteLineaVenta(importeLineaVenta);
                BaseDatos.entityManager.persist(lineaVentaNueva);
                LineaVentaList.addLineaVenta(lineaVentaNueva);
            }
        }
        //Si todo esta correcto, confirmamos la transaccion ,informamos al tableModel de los cambios
        // y cerramos la ventana
        if(correcto){    
            BaseDatos.entityManager.getTransaction().commit();            
            BaseDatos.entityManager.getTransaction().begin();

            if(conDatos){
                //Informamos de que se ha editado una fila
                Main.modelosTablas[5].fireTableRowsUpdated(Main.rowSelected, Main.rowSelected);                    
            }else{
                //Informamos de que se ha insertado una fila nueva y la seleccionamos por defecto
                Main.modelosTablas[5].fireTableRowsInserted(LineaVentaList.size()-1, LineaVentaList.size()-1);
                Main.tablas[5].setRowSelectionInterval(LineaVentaList.size()-1, LineaVentaList.size()-1);
            }
            //Llamamos al JDialog padre y lo cerramos.
            SwingUtilities.getWindowAncestor(this).setVisible(false);
            SwingUtilities.getWindowAncestor(this).dispose();
        }else{
            //Si no son correctos los datos, deshacemos los cambios e informamos al usuario
            BaseDatos.entityManager.getTransaction().rollback();
            BaseDatos.entityManager.getTransaction().begin();
            JOptionPane.showMessageDialog(this, "No se han podido guardar los datos, compruebe los campos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_boton_Guardar_LineaVentaActionPerformed

    private void botonVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVentaActionPerformed
        JDialog editor = new JDialog();        
        EditarVenta editarVenta = new EditarVenta(false);
        editor.add(editarVenta);
        editor.setModal(true);
        editor.setLocationRelativeTo(this.getParent());
        editor.pack();
        editor.setVisible(true);
        jComboBox1.setModel(new DefaultComboBoxModel(VentaList.getArray()));
    }//GEN-LAST:event_botonVentaActionPerformed

    private void botonArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonArticuloActionPerformed
        JDialog editor = new JDialog();        
        EditarArticulo editarArticulo = new EditarArticulo(false);
        editor.add(editarArticulo);
        editor.setModal(true);
        editor.setLocationRelativeTo(this.getParent());
        editor.pack();
        editor.setVisible(true);
        jComboBox1.setModel(new DefaultComboBoxModel(ArticuloList.getArray()));
    }//GEN-LAST:event_botonArticuloActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonArticulo;
    private javax.swing.JButton botonVenta;
    private javax.swing.JButton boton_Cancelar_LineaVenta;
    private javax.swing.JButton boton_Guardar_LineaVenta;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
