/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import BaseDatos.BaseDatos;
import BaseDatos.Values;
import Clases.Articulo;
import Clases.ArticuloList;
import Clases.Categoria;
import Clases.CategoriaList;
import Clases.Marca;
import Clases.MarcaList;
import Clases.Proveedor;
import Clases.ProveedorList;
import Renders.ComboBoxRender;
import Renders.ControlCaracteres;
import java.math.BigDecimal;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Manuel Cañamaque
 */
public class EditarArticulo extends javax.swing.JPanel {
    Articulo articulo;
    boolean conDatos;
    /**
     * Creates new form EditarArticulo
     * @param conDatos
     */
    public EditarArticulo(boolean conDatos) {
        initComponents();        
        this.conDatos=conDatos; 
        
        //Añadir ComboBox y Renders
        jComboBox1.setModel(new DefaultComboBoxModel(MarcaList.getArray()));
        jComboBox1.setRenderer(new ComboBoxRender());
        jComboBox2.setModel(new DefaultComboBoxModel(CategoriaList.getArray()));
        jComboBox2.setRenderer(new ComboBoxRender());
        jComboBox3.setModel(new DefaultComboBoxModel(ProveedorList.getArray()));
        jComboBox3.setRenderer(new ComboBoxRender());
        
        //Asignar Documents a los campos de texto.
        jTextField1.setDocument(new ControlCaracteres(Values.nombre_Articulo));        
        jTextField2.setDocument(new ControlCaracteres(Values.descripcion_Articulo));
        jTextField3.setDocument(new ControlCaracteres(Values.existencias_Articulo));
        jTextField4.setDocument(new ControlCaracteres(Values.precio_Articulo));
        
        //Obtenemos el articulo seleccionado y rellenamos los jTextFields si es para editar
        if(conDatos){            
            articulo = ArticuloList.getArticuloAt(Main.getRowSelected());
            jTextField1.setText(articulo.getNombre());
            jTextField2.setText(articulo.getDescripcion());
            jTextField3.setText(""+articulo.getExistencias());
            jTextField4.setText(""+articulo.getPrecio());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        boton_Guardar_Articulo = new javax.swing.JButton();
        boton_Cancelar_Articulo = new javax.swing.JButton();
        botonMarca = new javax.swing.JButton();
        botonCategoria = new javax.swing.JButton();
        botonProveedor = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Nombre:");

        jTextField1.setColumns(20);

        jLabel2.setText("Descripción:");

        jTextField2.setColumns(20);

        jLabel3.setText("Marca:");

        jLabel4.setText("Categoria:");

        jLabel5.setText("Proveedor:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Existencias:");

        jLabel7.setText("Precio:");

        jTextField3.setColumns(10);

        jTextField4.setColumns(20);

        boton_Guardar_Articulo.setText("Guardar");
        boton_Guardar_Articulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Guardar_ArticuloActionPerformed(evt);
            }
        });

        boton_Cancelar_Articulo.setText("Cancelar");
        boton_Cancelar_Articulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Cancelar_ArticuloActionPerformed(evt);
            }
        });

        botonMarca.setText("..Nueva");
        botonMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMarcaActionPerformed(evt);
            }
        });

        botonCategoria.setText("..Nueva");
        botonCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCategoriaActionPerformed(evt);
            }
        });

        botonProveedor.setText("..Nuevo");
        botonProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botonProveedor))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botonMarca))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botonCategoria))))))
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(36, 36, 36)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boton_Guardar_Articulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton_Cancelar_Articulo)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonMarca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonProveedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_Guardar_Articulo)
                    .addComponent(boton_Cancelar_Articulo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void boton_Cancelar_ArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Cancelar_ArticuloActionPerformed
        int result = JOptionPane.showConfirmDialog(this, 
        "¿Está seguro de que desea salir sin guardar los cambios?","Salir sin guardar", JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_OPTION){
            
            SwingUtilities.getWindowAncestor(this).setVisible(false);
            SwingUtilities.getWindowAncestor(this).dispose();
        }        
    }//GEN-LAST:event_boton_Cancelar_ArticuloActionPerformed

    private void boton_Guardar_ArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Guardar_ArticuloActionPerformed
        boolean correcto=true;
        // Comenzamos una nueva transaccion si no hay ninguna activa
        if(!BaseDatos.entityManager.getTransaction().isActive()){
            BaseDatos.entityManager.getTransaction().begin();
        }
        //Comprobamos que los campos no estan vacios.
        if("".equals(jTextField1.getText()) || "".equals(jTextField2.getText())
            || "".equals(jTextField3.getText()) || "".equals(jTextField4.getText())){
            correcto=false;
        }else{
            int existencias = 0;
            BigDecimal precio = null;
            try {
                existencias = Integer.valueOf(jTextField3.getText());
                precio = BigDecimal.valueOf(Double.valueOf(jTextField4.getText()));
            } catch (NumberFormatException e) {
                correcto=false;        
            }
            //Si es para editar, asignamos los valores al articulo.
            if(conDatos){
                articulo.setNombre(jTextField1.getText());
                articulo.setDescripcion(jTextField2.getText());
                articulo.setMarca((Marca)jComboBox1.getSelectedItem());
                articulo.setCategoria((Categoria)jComboBox2.getSelectedItem());
                articulo.setProveedor((Proveedor)jComboBox3.getSelectedItem());                
                articulo.setExistencias(existencias);                
                articulo.setPrecio(precio);                
                BaseDatos.entityManager.merge(articulo);
            }else{
                //Si es un articulo nuevo, lo creamos, le cambiamos los datos y lo guardamos
                Articulo articuloNuevo= new Articulo();
                articuloNuevo.setNombre(jTextField1.getText());
                articuloNuevo.setDescripcion(jTextField2.getText());
                articuloNuevo.setMarca((Marca)jComboBox1.getSelectedItem());
                articuloNuevo.setCategoria((Categoria)jComboBox2.getSelectedItem());
                articuloNuevo.setProveedor((Proveedor)jComboBox3.getSelectedItem());
                articuloNuevo.setExistencias(Integer.valueOf(jTextField3.getText()));
                articuloNuevo.setPrecio(BigDecimal.valueOf(Double.valueOf(jTextField4.getText())));
                BaseDatos.entityManager.persist(articuloNuevo);
                ArticuloList.addArticulo(articuloNuevo);
            }
        }
        //Si todo esta correcto, confirmamos la transaccion ,informamos al tableModel de los cambios
        // y cerramos la ventana
        if(correcto){    
            BaseDatos.entityManager.getTransaction().commit();            
            BaseDatos.entityManager.getTransaction().begin();

            if(conDatos){
                //Informamos de que se ha editado una fila
                Main.modelosTablas[4].fireTableRowsUpdated(Main.rowSelected, Main.rowSelected);                    
            }else{
                //Informamos de que se ha insertado una fila nueva y la seleccionamos por defecto
                Main.modelosTablas[4].fireTableRowsInserted(ArticuloList.size()-1, ArticuloList.size()-1);
                Main.tablas[4].setRowSelectionInterval(ArticuloList.size()-1, ArticuloList.size()-1);
            }
            //Llamamos al JDialog padre y lo cerramos.
            SwingUtilities.getWindowAncestor(this).setVisible(false);
            SwingUtilities.getWindowAncestor(this).dispose();
        }else{
            //Si no son correctos los datos, deshacemos los cambios e informamos al usuario
            BaseDatos.entityManager.getTransaction().rollback();
            BaseDatos.entityManager.getTransaction().begin();
            JOptionPane.showMessageDialog(this, "No se han podido guardar los datos, compruebe los campos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_boton_Guardar_ArticuloActionPerformed

    private void botonMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMarcaActionPerformed

        JDialog editor = new JDialog();        
        EditarMarca editarMarca = new EditarMarca(false);
        editor.add(editarMarca);
        editor.setModal(true);
        editor.setLocationRelativeTo(this.getParent());
        editor.pack();
        editor.setVisible(true);
        jComboBox1.setModel(new DefaultComboBoxModel(MarcaList.getArray()));
    }//GEN-LAST:event_botonMarcaActionPerformed

    private void botonCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCategoriaActionPerformed
        JDialog editor = new JDialog();        
        EditarCategoria editarCategoria = new EditarCategoria(false);
        editor.add(editarCategoria);
        editor.setModal(true);
        editor.setLocationRelativeTo(this.getParent());
        editor.pack();
        editor.setVisible(true);
        jComboBox2.setModel(new DefaultComboBoxModel(CategoriaList.getArray()));
    }//GEN-LAST:event_botonCategoriaActionPerformed

    private void botonProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProveedorActionPerformed
        JDialog editor = new JDialog();        
        EditarProveedor editarProveedor = new EditarProveedor(false);
        editor.add(editarProveedor);
        editor.setModal(true);
        editor.setLocationRelativeTo(this.getParent());
        editor.pack();
        editor.setVisible(true);
        jComboBox3.setModel(new DefaultComboBoxModel(ProveedorList.getArray()));
    }//GEN-LAST:event_botonProveedorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCategoria;
    private javax.swing.JButton botonMarca;
    private javax.swing.JButton botonProveedor;
    private javax.swing.JButton boton_Cancelar_Articulo;
    private javax.swing.JButton boton_Guardar_Articulo;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
